CREATE TABLE USERINFORMATION (
  PHONE NUMBER NOT NULL,
  FIRSTNAME VARCHAR(255) NOT NULL,
  LASTNAME VARCHAR(255),
  EMAIL VARCHAR(255) NOT NULL,
  CITY VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE VARCHAR(255) NOT NULL,
  CONSTRAINT USER_PK PRIMARY KEY (PHONE)
);


CREATE TABLE PARKINGINFORMATION (
  PARKINGID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL,
  PARKINGNAME VARCHAR(255) NOT NULL,
  PARKINGADDRESS VARCHAR(255) NOT NULL,
  PARKINGOWNER VARCHAR(255) NOT NULL,
  PARKINGOWNERPHONE NUMBER NOT NULL,
  PARKINGMANAGER VARCHAR(255) NOT NULL,
  PARKINGMANAGERPHONE NUMBER NOT NULL,
  PARKINGCITY VARCHAR(255) NOT NULL,
  TWOWHEELERTOTALCOUNT NUMBER NOT NULL,
  FOURWHEELERTOTALCOUNT NUMBER NOT NULL,
  TWOWHEELERPARKINGRATE NUMBER NOT NULL,	
  FOURWHEELERPARKINGRATE NUMBER NOT NULL,
  CONSTRAINT PARKING_PK PRIMARY KEY (PARKINGID)
);


CREATE TABLE BOOKING (
  BOOKINGID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL,
  USERPHONE NUMBER NOT NULL,
  PARKINGID NUMBER NOT NULL,
  PARKINGCITY VARCHAR(255) NOT NULL,
  VEHICLETYPE VARCHAR(255) NOT NULL,
  VEHICLEREGISTRATIONNUMBER VARCHAR(255) NOT NULL,
  BOOKINGDATE VARCHAR(255) NOT NULL,
  PARKINGSTARTDATETIME VARCHAR(255) NOT NULL,
  PARKINGENDDATETIME VARCHAR(255) NOT NULL,
  TOTALPARKINGHOURS NUMBER NOT NULL,
  BILLAMOUNT NUMBER NOT NULL,
  CONSTRAINT BOOKING_PK PRIMARY KEY (BOOKINGID)
);